# Generated by Django 3.2.4 on 2021-07-03 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requireditem",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requireditem",
            name="state",
            field=models.CharField(
                choices=[
                    ("InvalidState", "Invalidstate"),
                    ("CancelledState", "Cancelledstate"),
                    ("CollectingState", "Collectingstate"),
                    ("DoneState", "Donestate"),
                ],
                default="CollectingState",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("InvalidState", "Invalidstate"),
                            ("CancelledState", "Cancelledstate"),
                            ("PendingApprovalState", "Pendingapprovalstate"),
                            ("PendingDispatchState", "Pendingdispatchstate"),
                            ("PendingDeliveryState", "Pendingdeliverystate"),
                            ("DoneState", "Donestate"),
                        ],
                        default="PendingApprovalState",
                        max_length=64,
                    ),
                ),
                ("excepted_delivery_date", models.DateField(null=True)),
                ("events", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="share.requireditem",
                    ),
                ),
            ],
        ),
    ]
